from . import school
from . import room
from . import department
from . import role
from . import user
from . import employee
from . import teacher
from . import student
from . import program
from . import course
from . import course_selection
from . import student_plan_item
from . import grade
from . import active_course
